application: parcelabler 
version: 7
runtime: php55
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /javascripts
  static_dir: javascripts
- url: /.*
  script: index.php
